bufete_aplicacion:
    resource: "@BufeteAplicacionBundle/Resources/config/routing.yml"
    prefix:   /gestion/

bufete_main:
    resource: "@BufeteMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
